### PR TITLE
Adding service, env, version tags to email

### PR DESCRIPTION
**Pull request by mayabose**
## Description
Adding service, env, version tags to emails being sent through AWS. Updated unit tests as well. The tags should show up in Datadog for analysis. 

## Checklist
- [ ] Provided ticket and description
- [ ] Provided screenshots/demo
- [ ] Provided testing information
- [ ] Provided adequate test coverage for all new code
- [ ] Added PR reviewers

### CODE REVIEW

**Comment by mayabose** [comment]
Not sure if there's a way to test if the tags will appear correctly in Datadog before adding the changes?

**Review by TylerHendrickson — CHANGES_REQUESTED** [review]
@mayabose This looks good! I would suggest mocking the relevant environment variables to ensure they are consistently being included as you'd expect. This involves a bit of setup, but you can follow these steps to see what's going on.

First, you need to capture the starting values of the relevant environment variables before any tests are executed, because you'll need to restore them back to those starting values after the tests are complete. This file already has that being done for other environment variables, currently on [lines 14-29](https://github.com/usdigitalresponse/usdr-gost/blob/b96cfbc6eb145a07862da054b1cc82590b92e50a/packages/server/__tests__/email/email.test.js#L14-L29). You'll want to add the three `DD_`-prefixed environment variables to that set of constants, e.g.:
```js
const {
    TEST_EMAIL_RECIPIENT,

    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_DEFAULT_REGION,
    AWS_REGION,
    NOTIFICATIONS_EMAIL,
    SES_CONFIGURATION_SET_DEFAULT,

    NODEMAILER_HOST,
    NODEMAILER_PORT,
    NODEMAILER_EMAIL,
    NODEMAILER_EMAIL_PW,
    SHARE_TERMINOLOGY_ENABLED,

    DD_SERVICE,
    DD_ENV,
    DD_VERSION,
} = process.env;
```

Next, you'll want to alter the `describe('Email sender')` test suite to do two things:
1. Before running the suite, set new, predictable values for the `DD_`-prefixed env vars that you can reference in your tests.
2. After running the suite, restore those environment variables back to their original values.

These two steps happen in the `before()` and `after()` hooks, respectively, which are currently defined on [lines 214-219](https://github.com/usdigitalresponse/usdr-gost/blob/b96cfbc6eb145a07862da054b1cc82590b92e50a/packages/server/__tests__/email/email.test.js#L214-L219). You'll want to alter them as mentioned above, e.g.:
```js
    before(async () => {
        await fixtures.seed(db.knex);
        process.env.DD_SERVICE = 'test-dd-service';
        process.env.DD_ENV = 'test-dd-env';
        process.env.DD_VERSION = 'test-dd-version';
    });
    after(async () => {
        await db.knex.destroy();
        process.env.DD_SERVICE = DD_SERVICE;
        process.env.DD_ENV = DD_ENV;
        process.env.DD_VERSION = DD_VERSION;
    });
```

If you run the tests at this point, you will see that they are now failing due to errors like this:
``` 
  1) Email sender
       send passcode email
         calls the transport function with appropriate parameters:

      AssertionError: expected { fromName: 'USDR Grants', …(5) } to deeply equal { fromName: 'USDR Grants', …(5) }
      + expected - actual

           "notification_type=passcode"
           "user_role=staff"
           "organization_id=0"
           "team_id=0"
      -    "service=test-dd-service"
      +    "service=undefined"
           "env=test-dd-env"
           "version=test-dd-version"
         ]
```

So the final step is to update the places where you are asserting the inclusion of the new `service`, `env`, and `version` tag values. Here's an example of an altered test assertion that takes into account the newly-"mocked" values:
```js
    context('send passcode email', () => {
        it('calls the transport function with appropriate parameters', async () => {
            const sendFake = sinon.fake.returns('foo');
            sinon.replace(emailService, 'getTransport', sinon.fake.returns({ sendEmail: sendFake }));

            await email.sendPassCodeEmail('staff.user@test.com', '83c7c74a-6b38-4392-84fa-d1f3993f448d', 'https://api.grants.usdigitalresponse.org');

            expect(sendFake.calledOnce).to.equal(true);
            expect(_.omit(sendFake.firstCall.args[0], ['body'])).to.deep.equal({
                fromName: 'USDR Grants',
                ccAddress: undefined,
                toAddress: 'staff.user@test.com',
                subject: 'USDR Grants Tool Access Link',
                text: 'Your link to access USDR\'s Grants tool is https://api.grants.usdigitalresponse.org/api/sessions?passcode=83c7c74a-6b38-4392-84fa-d1f3993f448d. It expires in 30 minutes',
                tags: ['notification_type=passcode', 'user_role=staff', 'organization_id=0', 'team_id=0', 'service=my-dd-service', 'env=test-dd-env', 'version=test-dd-version'],
            });
            expect(sendFake.firstCall.args[0].body).contains('<title>Login Passcode</title>');
        });
    });
```

**Tip:** It's pretty easy to make these modifications quickly by doing a few find-and-replace operation on this file, e.g. replacing occurrences of `service=undefined` with `service=test-dd-service`.

**Comment by mayabose** [comment]
Thanks for the step-by-step guide!

**Review by TylerHendrickson — APPROVED** [review]
Changes look good – approved!

**Pull request merged**
