### PR TITLE
53 - add filters for grants table

### PR DESCRIPTION
**Pull request by romangurovich**
### Ticket #
#53 

### Description
Filters for 'My Grants' & 'Browse Grants' screens

### Screenshots / Demo Video

https://user-images.githubusercontent.com/648605/197889019-1a8b8d89-f077-46fa-9d24-aa53c546431b.mov

### Checklist
- [x] Provided ticket and description
- [x] Your PR title contains the ISSUE ticket number e.g "86: ..."
- [x] Provided screenshots/demo
- [ ] Provided testing information
- [ ] Provided adequate test coverage for all new code
- [x] Added PR reviewers
- [ ] Ensure at least 1 review before merging

### CODE REVIEW

**Comment by mhuang-usdr** [comment]
I can't tell from the video - is the Opportunity Status filter a multi-select?

**Comment by chrisxkeith** [comment]
@mhuang-usdr : I looked at the [Clickable prototype](https://www.figma.com/proto/ACzl0OlcPSL913vg2nezI9/Grants-ID-Tool?page-id=6%3A2537&node-id=6%3A2538&viewport=300%2C48%2C0.24&scaling=min-zoom&starting-point-node-id=6%3A2538), which shows all three drop-downs as multi-select. This can't be quite correct, since the third is Yes/No. Is the left-most the only multi-select.
@romangurovich : I pulled this branch, and the automated tests ran for me. I did an empty push to kick off another CI, and it looks like they passed this time.

**Comment by romangurovich** [comment]
> @mhuang-usdr : I looked at the [Clickable prototype](https://www.figma.com/proto/ACzl0OlcPSL913vg2nezI9/Grants-ID-Tool?page-id=6%3A2537&node-id=6%3A2538&viewport=300%2C48%2C0.24&scaling=min-zoom&starting-point-node-id=6%3A2538), which shows all three drop-downs as multi-select. This can't be quite correct, since the third is Yes/No. Is the left-most the only multi-select? @romangurovich : I pulled this branch, and the automated tests ran for me. I did an empty push to kick off another CI, and it looks like they passed this time.

I diverged from the prototype.
`OpportunityStatus` and `OpportunityCategory` are multiselect.
`Cost Sharing` is single select.

**Comment by mhuang-usdr** [comment]
Then experience looks good, I'll sign off on the PM side! Thanks Roman!

**Comment by chrisxkeith** [comment]
I read through the code changes, and don't see any red flags. I'm a little reluctant, however, to mark this as reviewed until the ARPA reporting period is over. I know this should not affect the ARPA code, but given what happened the last couple of days, I don't want any surprises.

**Comment by mhuang-usdr** [comment]
The last day of the reporting period is Monday

**Review by chrisxkeith — APPROVED** [review]

**Comment by mhuang-usdr** [comment]
🎉

**Pull request merged**
