### PR TITLE
build: fix node-gyp build in docker-compose (781)

### PR DESCRIPTION
**Pull request by LieAlbertTriAdrian**
### Ticket #
https://github.com/usdigitalresponse/usdr-gost/issues/781

### Description
There is an error to build node-gyp when you run `docker-compose up`

### Testing
Run `docker-compose up`  and you should see your app running like the screenshot below

Screenshot 2023-01-10 at 10 05 29 AM

### Checklist
- [x] Provided ticket and description
- [x] Your PR title contains the ISSUE ticket number e.g "86: ..."
- [x] Provided screenshots/demo
- [x] Provided testing information
- [x] Provided adequate test coverage for all new code
- [ ] Run automated tests (docker-compose exec app yarn test)
- [ ] Added PR reviewers
- [ ] Ensure at least 1 review before merging

### CODE REVIEW

**Comment by NatHillardUSDR** [comment]
Ah - this is the same fix I propose over at https://github.com/usdigitalresponse/usdr-gost/pull/782 actually !

**Comment by NatHillardUSDR** [comment]
If you could +1 on the other PR maybe we can close this as a dupe? Glad to see we arrived at the same solution for this issue!

**Comment by LieAlbertTriAdrian** [comment]
@NatHillardUSDR ah gotcha, I'll close this PR then

**Comment by LieAlbertTriAdrian** [comment]
@NatHillardUSDR I just got access to this repo. gave +1 on other PR!

**Pull request closed without merging**
