### PR TITLE
fix: #949 update interested grants count labels

### PR DESCRIPTION
**Pull request by adele-usdr**
Update totalRows and label to use counts that are filtered or not filtered properly.

#949 Unusual display in "Recent Activity" grid

### CODE REVIEW

**Comment by adele-usdr** [comment]
I got some local test failures so not sure yet if this is right.

**Comment by adele-usdr** [comment]
I'd also like to figure out how to add tests for this!

**Comment by TylerHendrickson** [comment]
> I'd also like to figure out how to add tests for this!

You and me both! 😆 

Unfortunately, the main `Finder` client-side code doesn't have a lot of coverage in its test suite; at present, the only tests that exist for the client-side are only covering the following parts of the `packages/client` path:
- `src/helpers/fetchApi`
- `src/helpers/featureFlags`
- `src/arpa_reporter`

I don't have a lot of background in maintaining this type of code, so I've been a bit reluctant to dive in on adding unit tests for client-side code without 1) someone on the team who can advise setting up a test suite, or 2) enough capacity to research and set things up accordingly. Given that this is a longstanding shortcoming of this part of the codebase, I don't think adding tests needs to block this PR, but it would be good to get to a point where fixes like these can have accompanying test cases to prevent future regressions.

**Review by TylerHendrickson — APPROVED** [review]
These changes look good to me – counts look correct when testing locally 🎉 
I also don't see any failures when running tests on my end.

**Pull request merged**
