### PR TITLE
feat: ensures scraper does not interfere with regular application usage

### PR DESCRIPTION
**Pull request by as1729**
### Description
As seen from the image below, there's a 50% increase in CPU usage when the grantssraper cron gets kicked off. This morning users have also complained that they were unable to login right when the scraper was running. All this leads me to believe that we should avoid the cron from running during business hours.

image

### Screenshots / Demo Video
N/A

### Testing
N/A - This works fine from testing in our staging and prod environments. We're moving away from node-cron so did not take the add'l effort to add new tests here.

### Checklist
- [x] Provided ticket and description
- [ ] Your PR title contains the ISSUE ticket number e.g "86: ..."
- [x] Provided screenshots/demo
- [x] Provided testing information
- [ ] Provided adequate test coverage for all new code
- [x] Run automated tests (docker compose exec app yarn test)
- [x] Added PR reviewers
- [ ] Ensure at least 1 review before merging

### CODE REVIEW

**Review by chrisxkeith — APPROVED** [review]

**Review by TylerHendrickson — CHANGES_REQUESTED** [review]
As discussed, let's modify the scraper cron to fire off once daily (iirc 1:30am ET).

**Comment by TylerHendrickson** [comment]
@as1729 Is this PR still needed?

**Comment by as1729** [comment]
I was thinking there's no harm in reducing the scraper frequency even if its only useful until the cutover to AWS. wdyt? Especially with email digest creation, it gives a bit more control over what processes are running at a given time.

**Comment by TylerHendrickson** [comment]
Sure, I'm in favor. Just wasn't sure if it was still an active PR :)

**Comment by as1729** [comment]
@TylerHendrickson ready for another reivew!

**Review by TylerHendrickson — APPROVED** [review]

**Pull request merged**
