### PR TITLE
New Card Container Design

### PR DESCRIPTION
**Pull request by mayabose**
## Description
This tickets applies a new card container design to the grant details page, creating a gray background and white cards to visually separate information. To accomplish this, new CardLayout and CardContainer components have been created and incorporated into the GrantDetailsView page. 

## Screenshots / Demo Video
Old UI:
image

New UI:
image

## Checklist
- [ ] Provided ticket and description
- [ ] Provided screenshots/demo
- [ ] Provided testing information
- [ ] Provided adequate test coverage for all new code
- [ ] Added PR reviewers

### CODE REVIEW

**Comment by mayabose** [comment]
This is more of a rough draft design-wise - I'm very open to tweaking the design as I know it's different than the original Figma design (though part of that is because the original has a few more elements that haven't been added yet, I believe). I think someone on the design team could offer input here into text styles/sizes, etc. I made this initial PR more for getting the components and implementation correctly set up before more styling is added.

**Comment by masimons** [comment]
@mayabose The implementation on the code side of things looks good to me! I think your idea to run it by design/product is a good one, since they would probably be able to comment on how much wider they would like the left card than the right card, the spacing between title and "View on Grants.gov" button, etc. Perhaps an additional prop will need be passed to CardContainer to specify wideness?

**Comment by mayabose** [comment]
Got rid of custom components as per the discussion with the design team. If anyone has any suggestions on getting a more adaptive <div> for the background, I'd love to hear them. The current height of the background div container is set to 200% so that the color fills the page when scrolling down, as it wasn't working with 100%.

**Review by TylerHendrickson — APPROVED** [review]
Looks good!

**Comment by masimons** [comment]
@mayabose following this, just wanted to say i'm sorry you had to scrap the CardContainer work in the end, but this looks really nice

**Comment by mayabose** [comment]
@masimons No problem about the scrapping, and thank you so much for all your contributions and help!

**Pull request merged**
