### PR TITLE
[DRAFT] fix: docker-compose up fails: error: Could not find any python instal…

### PR DESCRIPTION
**Pull request by NatHillardUSDR**
…lation to use (781)

Docker compose up is currently failing because of missing dependencies. This adds in the necessary dependencies.
I do think larger Docker and Docker-compose changes are probably warranted here, but keeping this fix small for now.

### Ticket #
#781 

### Description
Docker compose up is currently failing because of missing dependencies. This adds those in. It is a bit odd that a js dependency requires python, but apparently it does! 

### Screenshots / Demo Video
See error message from original issue

### Testing
Successfully ran `docker compose up` and did not see a failure. I did not test deployment scenarios as I'm not sure how to do this just yet, but this is definitely worth a check!

### Checklist
- [x] Provided ticket and description
- [x] Your PR title contains the ISSUE ticket number e.g "86: ..."
- [x] Provided screenshots/demo
- [x] Provided testing information
- [x] Provided adequate test coverage for all new code
- [x] Run automated tests (docker compose exec app yarn test)
- [x] Added PR reviewers
- [ ] Ensure at least 1 review before merging

### CODE REVIEW

**Comment by TylerHendrickson** [comment]
@NatHillardUSDR I didn't see mentioned anywhere- which JS dependency requires Python? Also, is it a dependency for runtime, build-time, or both?

**Comment by NatHillardUSDR** [comment]
A very good question, @TylerHendrickson ! 

https://github.com/usdigitalresponse/usdr-gost/issues/781 has the log, but its failing during the build phase for `@parcel/watcher`, because *this* depends on `node-gyp-build`, which, according to [its docs](https://github.com/nodejs/node-gyp#configuring-python-dependency) uses `python` under the hood. 

Specifically the dependencies go:
```
npm ls node-gyp-build 
cares-grant-opportunities@1.0.0 /Users/nhillard/Documents/Code/USDR/usdr-gost
└─┬ lerna@5.6.2
  └─┬ nx@14.8.3
    └─┬ @parcel/watcher@2.0.4
      └── node-gyp-build@4.5.0
```

This, in turn, is because `yarn setup` is `yarn install && yarn run bootstrap`, and `bootstrap` is `lerna bootstrap` in `package.json` .

Arguably here, `lerna bootstrap` is not necessary, as we're not relying on the inter-package dependencies that `lerna` optimizes for. This is maybe a bigger change though and potentially has other fallout. 

As a shorter-term workaround I guess the above works, but maybe I can add a comment about the somewhat convoluted path that led to this being necessary

**Comment by TylerHendrickson** [comment]
@NatHillardUSDR The missing piece for me is still understanding what specific dependency change is now requiring this. I don't fundamentally have an issue with adding Python to the build deps, but I'd like to first understand how the need became introduced. As you noted, there's something of a convoluted dependency chain here, and I'm wondering whether this issue ought to be resolved through simplifying some of these needs.

**Comment by NatHillardUSDR** [comment]
> @NatHillardUSDR The missing piece for me is still understanding what specific dependency change is now requiring this. I don't fundamentally have an issue with adding Python to the build deps, but I'd like to first understand how the need became introduced. As you noted, there's something of a convoluted dependency chain here, and I'm wondering whether this issue ought to be resolved through simplifying some of these needs.

I can look into removing `lerna bootstrap` - based on [the docs](https://github.com/lerna/lerna/tree/main/commands/bootstrap) for this command it seems to not have much benefit, in our scenario, over `yarn install`. I can test this out and see how it might impact things

**Review by LieAlbertTriAdrian — APPROVED** [review]

**Comment by NatHillardUSDR** [comment]
Moving back to draft to consider alternative fix for this, likely involving removing lerna dep in this particular instance

**Comment by TylerHendrickson** [comment]
Removing myself as a reviewer while this is in draft state. Please feel free to re-add me once you're ready for another review!

**Pull request closed without merging**
